# render.yaml
services:
  - type: web
    name: secure-auth-flask
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free

databases:
  - name: secureauthdb
    databaseName: secureauth
    user: secureauthuser
    plan: free